import { motion } from 'framer-motion';
import { AlertTriangle, Zap, Satellite, Navigation, Radio as RadioIcon } from 'lucide-react';

export default function Alerts() {
  const alerts = [
    { severity: 'High', class: 'X2.2', time: '10 mins ago', impact: 'High Frequency Radio Blackout (R3). Satellite drag increased. Aviation communication disruption likely.', icon: RadioIcon, color: 'text-red-500', border: 'border-red-500/30', bg: 'bg-red-500/10' },
    { severity: 'Medium', class: 'M4.1', time: '2 hours ago', impact: 'Minor GPS degradation on sunlit side. Small satellite orientation issues possible.', icon: Navigation, color: 'text-orange-500', border: 'border-orange-500/30', bg: 'bg-orange-500/10' },
    { severity: 'Low', class: 'C8.0', time: '5 hours ago', impact: 'No significant impact on Earth-based systems. Background X-ray flux elevated.', icon: Satellite, color: 'text-yellow-500', border: 'border-yellow-500/30', bg: 'bg-yellow-500/10' },
  ];

  return (
    <div className="max-w-4xl mx-auto py-10">
      <div className="flex items-center gap-3 mb-4">
        <AlertTriangle className="w-8 h-8 text-red-500" />
        <h1 className="text-3xl font-bold tracking-tight">Alerts & Space Weather Impact</h1>
      </div>
      <p className="text-slate-400 mb-8">Recent alerts generated by SuryaFlare AI and their projected impacts on Earth systems.</p>
      
      <div className="space-y-6">
        {alerts.map((alert, i) => {
          const Icon = alert.icon;
          return (
            <motion.div 
              key={i} 
              initial={{ opacity: 0, x: -20 }} 
              animate={{ opacity: 1, x: 0 }} 
              transition={{ delay: i * 0.1 }} 
              className={`glass-panel p-6 border ${alert.border} flex flex-col md:flex-row gap-6 items-start md:items-center`}
            >
              <div className={`p-4 rounded-full ${alert.bg} flex-shrink-0`}>
                <Icon className={`w-8 h-8 ${alert.color}`} />
              </div>
              <div className="flex-grow">
                <div className="flex items-center gap-3 mb-1">
                  <span className={`px-2 py-0.5 rounded text-xs font-bold uppercase tracking-wider ${alert.bg} ${alert.color}`}>
                    {alert.severity} Risk
                  </span>
                  <span className="text-sm text-slate-400">{alert.time}</span>
                </div>
                <h3 className="text-xl font-bold text-slate-200 mb-2">Class {alert.class} Flare Detected</h3>
                <p className="text-slate-300 text-sm leading-relaxed">
                  <strong className="text-white">Projected Impact:</strong> {alert.impact}
                </p>
              </div>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}
